/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab8_jonrryenamorado;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author wende
 */
public class principal extends javax.swing.JFrame {

    
    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opciones = new javax.swing.JPopupMenu();
        depedir = new javax.swing.JMenuItem();
        cambiar = new javax.swing.JMenuItem();
        ascender = new javax.swing.JMenuItem();
        mensajes = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        tab1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        gg1 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        padre = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        emp_name = new javax.swing.JTextField();
        emp_id = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        gg_id = new javax.swing.JTextField();
        gg_sal = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        emp_sal = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        emp_puesto = new javax.swing.JComboBox<>();
        gg_pass = new javax.swing.JPasswordField();
        emp_pass = new javax.swing.JPasswordField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tree = new javax.swing.JTree();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cb_de = new javax.swing.JComboBox<>();
        cb_para = new javax.swing.JComboBox<>();
        broadcast = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        mensaje = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        depedir.setText("Despedir");
        depedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depedirActionPerformed(evt);
            }
        });
        opciones.add(depedir);

        cambiar.setText("Cambiar con...");
        opciones.add(cambiar);

        ascender.setText("Ascender");
        opciones.add(ascender);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enviado por:", "Enviado a:", "Contenido"
            }
        ));
        jScrollPane3.setViewportView(tabla);

        javax.swing.GroupLayout mensajesLayout = new javax.swing.GroupLayout(mensajes.getContentPane());
        mensajes.getContentPane().setLayout(mensajesLayout);
        mensajesLayout.setHorizontalGroup(
            mensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
        );
        mensajesLayout.setVerticalGroup(
            mensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tab1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tab1StateChanged(evt);
            }
        });

        jLabel19.setText("Gerente General: ");

        jButton7.setText("Crear Gerente");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Crear Empleado");

        jLabel21.setText("Pertenece a:");

        jLabel22.setText("Nombre:");

        jLabel23.setText("ID:");

        jLabel24.setText("Password:");

        emp_name.setEnabled(false);

        emp_id.setEnabled(false);

        jButton8.setText("Agregar");
        jButton8.setEnabled(false);
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        jLabel12.setText("ID");

        jLabel25.setText("Password:");

        jLabel26.setText("Salario: ");

        jLabel27.setText("Salario:");

        emp_sal.setEnabled(false);

        jLabel28.setText("Puesto:");

        emp_puesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerencia", "Empleado Pendejo" }));
        emp_puesto.setEnabled(false);

        emp_pass.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator4)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(99, 99, 99)
                                .addComponent(jLabel20))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(gg1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                    .addComponent(gg_id)
                                    .addComponent(gg_sal)
                                    .addComponent(gg_pass))
                                .addGap(42, 42, 42)
                                .addComponent(jButton7))
                            .addComponent(jLabel27))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(padre, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel24))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(emp_name)
                                    .addComponent(emp_id, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                    .addComponent(emp_sal)
                                    .addComponent(emp_puesto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(emp_pass))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                        .addComponent(jButton8)
                        .addGap(28, 28, 28))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(gg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(gg_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(gg_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(gg_sal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20))
                .addGap(9, 9, 9)
                .addComponent(padre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(emp_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emp_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emp_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(emp_sal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(emp_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton8)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 17, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tab1.addTab("Crear", jPanel2);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        tree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        tree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                treeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tree);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        tab1.addTab("Mostrar", jPanel6);

        jLabel1.setText("De: ");

        jLabel2.setText("Para:");

        cb_de.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_deItemStateChanged(evt);
            }
        });

        broadcast.setText("BROADCAST");
        broadcast.setEnabled(false);
        broadcast.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                broadcastItemStateChanged(evt);
            }
        });

        mensaje.setColumns(20);
        mensaje.setRows(5);
        jScrollPane1.setViewportView(mensaje);

        jLabel3.setText("Mensaje:");

        jButton1.setText("Enviar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("LOG");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cb_de, 0, 114, Short.MAX_VALUE)
                                    .addComponent(cb_para, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(broadcast)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jButton1)
                .addGap(94, 94, 94)
                .addComponent(jButton2)
                .addGap(0, 153, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cb_de, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cb_para, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(broadcast))
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        tab1.addTab("Mensajeria", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tab1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tab1)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        empleados p = new empleados(gg1.getText(), Long.parseLong(gg_id.getText()), gg_pass.getText(), null, Long.parseLong(gg_sal.getText()), "Gerente General");
        lista.add(p);
        DefaultComboBoxModel m = (DefaultComboBoxModel) padre.getModel();
        m.addElement(p);
        padre.setModel(m);
        gg1.setEnabled(false);
        gg_id.setEnabled(false);
        gg_pass.setEnabled(false);
        gg_sal.setEnabled(false);

        emp_name.setEnabled(true);
        emp_id.setEnabled(true);
        emp_pass.setEnabled(true);
        emp_sal.setEnabled(true);
        emp_puesto.setEnabled(true);
        jButton8.setEnabled(true);
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
        empleados p = new empleados(emp_name.getText(), Long.parseLong(emp_id.getText()), emp_pass.getText(), (empleados) padre.getSelectedItem(), Long.parseLong(emp_sal.getText()), emp_puesto.getSelectedItem().toString());
        lista.add(p);
        if (p.getPuesto().equals("Gerencia")) {

            DefaultComboBoxModel m = (DefaultComboBoxModel) padre.getModel();
            m.addElement(p);
            padre.setModel(m);
        }
        for (empleados t : lista) {
            if (t.getName().equals(p.getJefe().getName())) {
                t.getListaempleados().add(p);
            }
        }
    }//GEN-LAST:event_jButton8MouseClicked

    private void treeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treeMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            int row = tree.getClosestRowForLocation(evt.getX(), evt.getY());
            tree.setSelectionRow(row);
            Object v1 = tree.getSelectionPath().getLastPathComponent();

            nodo_seleccionado = (DefaultMutableTreeNode) v1;
            empleado_sel = (empleados) nodo_seleccionado.getUserObject();
            opciones.show(evt.getComponent(), evt.getX(), evt.getY());

        }
    }//GEN-LAST:event_treeMouseClicked
    empleados global = new empleados();
    private void tab1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tab1StateChanged
        // TODO add your handling code here:
        if (tab1.getSelectedIndex() == 1) {
            global = new empleados();
            global = lista.get(0);
            DefaultMutableTreeNode root = new DefaultMutableTreeNode(global);
            listar_tree(global, root);

            DefaultTreeModel m = new DefaultTreeModel(root);
            tree.setModel(m);
        }
        if (tab1.getSelectedIndex() == 2) {
            DefaultComboBoxModel c = new DefaultComboBoxModel(lista.toArray());
            cb_de.setModel(c);
            
            DefaultComboBoxModel f = new DefaultComboBoxModel(lista.toArray());
            f.removeElementAt(0);
            cb_para.setModel(f);
            broadcast.setEnabled(true);

        }


    }//GEN-LAST:event_tab1StateChanged

    private void depedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depedirActionPerformed
        // TODO add your handling code here:
        int x = 0;
        for (empleados t : lista) {
            if (t.getName().equals(empleado_sel.getName())) {
                if (t.getPuesto().equals("Gerencia") && !t.getListaempleados().isEmpty()) {
                    empleados temp = t.getListaempleados().get(t.getListaempleados().size() - 1);
                    for (empleados p : t.getListaempleados()) {
                        p.setJefe(temp);
                    }
                    temp.setJefe(t.getJefe());
                    lista.set(x, temp);
                    global = new empleados();

                }

            }
            x++;
        }
        global = new empleados();
        global = lista.get(0);
        DefaultMutableTreeNode root = new DefaultMutableTreeNode(global);
        listar_tree(global, root);

        DefaultTreeModel m = new DefaultTreeModel(root);
        tree.setModel(m);
        nodo_seleccionado.setUserObject(evt);

    }//GEN-LAST:event_depedirActionPerformed

    private void cb_deItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_deItemStateChanged
        // TODO add your handling code here:
        DefaultComboBoxModel m = new DefaultComboBoxModel(lista.toArray());
        m.removeElement(cb_de.getSelectedItem());
        cb_para.setModel(m);
        empleados tmp = (empleados) cb_de.getSelectedItem();
        if (tmp.getPuesto().equals("Gerencia") || tmp.getPuesto().equals("Gerente General")) {
            broadcast.setEnabled(true);
        } else {
            broadcast.setEnabled(false);
        }

    }//GEN-LAST:event_cb_deItemStateChanged

    private void broadcastItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_broadcastItemStateChanged
        // TODO add your handling code here:
        if (broadcast.isSelected()) {
            cb_para.setEnabled(false);
        } else {
            cb_para.setEnabled(true);

        }
    }//GEN-LAST:event_broadcastItemStateChanged

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        if (broadcast.isSelected()) {
            mensajes nm = new mensajes();
            nm.setCifrado(false);
            nm.setFuente(cb_de.getSelectedItem().toString());
            ArrayList destino = ((empleados) cb_de.getSelectedItem()).getListaempleados();
            nm.setDestino(destino);
            nm.setMensaje(mensaje.getText());
            adminMensajes am = new adminMensajes("./mensajes.rt");
            am.cargarArchivo();
            am.setMensaje(nm);
            am.escribirArchivo();
            JOptionPane.showMessageDialog(rootPane, "MENSAJE ENVIADO");
        } else {
            mensajescifrados nmc = new mensajescifrados();
            nmc.setCifrado(true);
            nmc.setFuente(cb_de.getSelectedItem().toString());
            nmc.setDestino(cb_para.getSelectedItem().toString());
            nmc.setMensaje(mensaje.getText());
            codificar(nmc);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        adminMensajes am = new adminMensajes("./mensajes.rt");
        am.cargarArchivo();
        DefaultTableModel m = (DefaultTableModel) tabla.getModel();
        
        for (mensajes t : am.getListaMensajes()) {
            String destiny = "";
            for (Object i : t.getDestino()) {
                destiny += ((empleados)i).getName();
            }
            Object row[] = {t.getFuente(), destiny, t.getMensaje()};
            m.addRow(row);
        }
        tabla.setModel(m);
        mensajes.setModal(true);
        mensajes.pack();
        mensajes.setLocationRelativeTo(this);
        mensajes.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    public void codificar(mensajescifrados nmc) {
        String[] count = new String[nmc.getMensaje().length() - 1];
        count = nmc.getMensaje().split("(?!^)");

        ArrayList<letras> tabla = new ArrayList();
        for (String t : count) {
            int x = 0;

            for (String t2 : count) {

                if (t.equals(t2)) {
                    x++;
                }
            }

            tabla.add(new letras(t, x));

        }
        System.out.println(tabla);
        letras swap;
        int length = tabla.size();
        for (int i = 0; i < length; i++) {
            for (int j = i + 1; j < length; j++) {
                if (tabla.get(i).getLetra().equals(tabla.get(j).getLetra())) {
                    int temp = j;
                    for (int k = temp; k < length - 1; k++) {
                    	tabla.set(k, tabla.get(k+1));
                    }
                    j--;
                    length--;
 
                }
            }
        }

        for (int i = 0; i < tabla.size() - 1; i++) {
            for (int j = 0; j < tabla.size() - 1; j++) {
                if (tabla.get(j).getNumber() > tabla.get(j + 1).getNumber()) {
                    swap = tabla.get(j);
                    tabla.set(j, tabla.get(j + 1));
                    tabla.set(j + 1, swap);
                }
            }
        }
        System.out.println(tabla);

    }

    public void listar_tree(empleados p_raiz, DefaultMutableTreeNode nodo) {
        try {

            ArrayList<empleados> l3 = p_raiz.getListaempleados();

            for (empleados temp : l3) {
                if (temp.getListaempleados().isEmpty()) {
                    DefaultMutableTreeNode n = new DefaultMutableTreeNode(temp);
                    nodo.add(n);
                } else {
                    DefaultMutableTreeNode n = new DefaultMutableTreeNode(temp);
                    nodo.add(n);
                    listar_tree(temp, n);

                }
            }
        } catch (Exception e) {
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ascender;
    private javax.swing.JCheckBox broadcast;
    private javax.swing.JMenuItem cambiar;
    private javax.swing.JComboBox<String> cb_de;
    private javax.swing.JComboBox<String> cb_para;
    private javax.swing.JMenuItem depedir;
    private javax.swing.JTextField emp_id;
    private javax.swing.JTextField emp_name;
    private javax.swing.JPasswordField emp_pass;
    private javax.swing.JComboBox<String> emp_puesto;
    private javax.swing.JTextField emp_sal;
    private javax.swing.JTextField gg1;
    private javax.swing.JTextField gg_id;
    private javax.swing.JPasswordField gg_pass;
    private javax.swing.JTextField gg_sal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextArea mensaje;
    private javax.swing.JDialog mensajes;
    private javax.swing.JPopupMenu opciones;
    private javax.swing.JComboBox<String> padre;
    private javax.swing.JTabbedPane tab1;
    private javax.swing.JTable tabla;
    private javax.swing.JTree tree;
    // End of variables declaration//GEN-END:variables
    ArrayList<empleados> lista = new ArrayList();
    DefaultMutableTreeNode nodo_seleccionado;
    empleados empleado_sel = new empleados();
}
